sudo: required
dist: trusty
services:
- docker
env:
  global:
  - PKGFORGE_STATEFILE=/tmp/pkgforge
  - secure: Pv8wctXGM1FkmPqy4x8VkcWvgvPMs79/ODF7AS0/NeT3pSBEhHc3oH2jEX0giErKM+w66AMasm6thEa//uJ7ag5APB6DO0x4BawdbWqkaxlYULjGmj3oEnqJDfJq0zvLaodTy+cgp+Xe8cdSi5106cPmmsen5gQHA6qxFNzij1wFp79TmAdXpvi/CljneRrkFU4OnSx6/I+GPq0pguZ/McZpps+UV1ABxN9xCmnS/eThzQ/taF1bDYzrFNNIGCF8+j5DdYib8x05EdXl7llorS5X3rDSB20fPiCvRDd0vmju4f40a/CuKRMXdOuUZdlI7PWlv/aDlZs/pK0Iiwb/RRIehnUF+A/jEPs5RmCm0jUkHXpOBzy6/+Wl5tyhwg4REOSZ+r1IuWDkz3IBbU3ymHMDh+KJKckK4e1fYYxbl+bSd/1ZqT5rbJg2XOBCrB8plYLlepxThJ3msT49qV1UgAfD9nZQoDp/xO03Ztr5TLcHvGFgPiMJQpHKwBwxtu+ljThZ+lsJyyjZqs6qHINfPIKcXetYxaSBpqIIA8pvTi7QwVBatTySh0AgP363+rSWoOdcyZWns6TFszpRlS+tK2H24Yr4CmQYSIJhdp2fFyXDSFvHZEydS+4GDxTgR8/CJ1RUQsgsju9l+vuoFdQwOZXA2Wp0e3qdZeE0ATbnB0c=
script: make
deploy:
  provider: script
  script: make release || travis_terminate 1
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
  slack:
    secure: YVs6XTGHOpJPpyOx9zs7cwqNy/42NnjuXozjRpTpr1mTv0J8Nyz+CTNS8e2xnQ0i6hzLJiRFuWEHo9lQWqErusiCOtvP1NOHxlhQlRIw43Y95xwc0HHqF7JspluZ64MPc6tepY1nS896T2MJZW/eqiwFzZsvEnXLXPtZ583xleJPxDLyMv3ymTue/LHNeCZ+4V55BKvM4L5+wB8sS3S8aT+ZLhtqCtQ73c3OP+ksqKJAJTslnHmwvJS4osuVSkgog5Ba3gPaenHwzClMEp4FWbCRtbb3mQysdAPPgFT5uG0LNQ0m9WYVUY4oEUnlpneuEiUfnknEu3w6VuaUPgbCx2il/YjuERTx+2/iLs0DqR/Q7VQ2kervF4LvPeVrAxEDlnsti2fCLArZPK6+LdxOhmAJML9IlG9yy+U+1wSFcZTxYh7HJ4iGkpw2DmU5RfRN9q9bMLOwJAVqpxmBJVOrkUYfiXOpdYG+FXj2aMn60WxWnAOMG2zXynCh0ZvpY6SNAtxL4zL6tD2B/hNhbGt8cbyiFDJLGJ+Mhyl4+/XnFT2bTtA4nOCYgtXOIU6p6B44VvbBlV7OMUkZcE924RlitglvHQ+ydXWNod0lYGhuVngZZHU5SvbTlnomXtgtaRensV923X/O8TVYxvub7D5UJVgo2IXdJABiUDjqNtsgiRc=
